### ISSUE TITLE
Does not work with Telegram Purple

### ISSUE THREAD

**Issue by rodneyrod** [jasuarez/minbif#1]
Steps:
Install Ubuntu 14.04, minbif, the dependencies for telegram-purple and then make install telegram-purple (https://github.com/majn/telegram-purple)

minbif currently doesn't know how to process the request code that Telegram needs when using a new client, entering any numbers results in the PM closing and reopening with no other changes.

Further, Telegram doesn't acknowledge connections through minbif as no verification code is sent.

**Comment by jasuarez** [comment]
Sorry, this is not the official minbif project homepage.

For issues, I suggest to file them at https://symlink.me/projects/minbif/issues

**Comment by rodneyrod** [comment]
@jasuarez 
Last update in the tracker was 18/04/2013 04:11 pm

Your code is much newer than that, and if I post it on the tracker I know that the 0 devs currently working on the project may see it, but what will really be done about it?

**Comment by jasuarez** [comment]
On Mon, 2016-06-27 at 03:12 -0700, rodneyrod wrote:

> @jasuarez 
> Last update in the tracker was 18/04/2013 04:11 pm
> Your code is much newer than that, and if I post it on the tracker I
> know that the 0 devs currently working on the project may see it, but
> what will really be done about it?
>  

The code in my repo is mostly the same as latest minbif version, except
it has a couple of commits I need for my personal usage. But other than
that, it is the same as minbif.

Thing is that unfortunately I don't work on minbif. So creating an
issue here is pointless: I won't work on it, and nobody will notice
such issue.

To be honest, I would file the bug anyway in minbif. Other people could
see it and maybe someone can suggest you a workaround.

Other than that, pitty the project is not maintained any more.
